# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

#- name: Build and push Docker image
#  uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#  with:
#    context: .
#    file: ./Dockerfile
#    platforms: ${{ matrix.platforms }}
#    push: true
#    outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image



name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags:  ghcr.io/Tanktwo/logrotate:latest